name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '**' # Pour exécuter les tests sur toutes les branches
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, bcmath, zip
          tools: composer
          
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name : Copy .env File 
        run : cp .env.example .env

      - name : Generate Application Key
        run : php artisan key:generate

     

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps: 

      - name: Debug Current Directory
        run: pwd && ls -la

      - name: Install Dependencies
        run: composer install

      - name: Run Laravel Tests
        run: php artisan test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/laravel-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/laravel-app:${{ github.sha }}
